path: 'https://test-stand.gb.ru/gateway/login'
username: 'benya11'
password: '696a4d2aa3'
title: 'Казахский доктор Стрендж'
description: 'Как россиянин съездил в Казахстан ради "Доктора Стрэнджа"'
content: 'Житель РФ Дмитрий Бутырин на автомобиле поехал в Павлодар, чтобы увидеть фильм "Доктор Стрэндж: В мультивселенной безумия", передает inbusiness.kz.    '